sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strict.focus.anc.X0.igb.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.union.sum.0X.igb.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.union.anc.perc.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.union.sum.X0.igb.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strict.focus.anc.perc.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.union.sum.XX.igb.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.sum.XX.igb.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strict.sum.X0.igb.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strict.focus.anc.num.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strict.sum.XX.igb.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.union.sum.igb.index.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strict.focus.anc.igb.index.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strict.sum.0X.igb.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strictAgg.anc.perc.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.anc.num.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strictAgg.anc.0X.igb.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strict.anc.perc.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.sum.igb.index.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strictAgg.anc.igb.index.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.union.anc.num.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.anc.perc.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strictAgg.anc.XX.igb.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strict.anc.num.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strict.focus.anc.0X.igb.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/summary.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strictAgg.anc.X0.igb.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strict.sum.igb.index.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strict.focus.anc.XX.igb.html
sed -i -f tmp.BaWCSlwbAU/./replace.sed tmp.BaWCSlwbAU/multovl.strictAgg.anc.num.html
