s:images/GimmeMotifs_6_random_roc.png:images.GimmeMotifs_6_random_roc.png:g
s:images/GimmeMotifs_7_histogram.svg:images.GimmeMotifs_7_histogram.svg:g
s:images/Motif.8.3.png:images.Motif.8.3.png:g
s:images/Motif.7.3.png:images.Motif.7.3.png:g
s:images/GimmeMotifs_1_random_roc.png:images.GimmeMotifs_1_random_roc.png:g
s:images/Average_26.png:images.Average_26.png:g
s:images/Meme_6_w6.png:images.Meme_6_w6.png:g
s:images/ABI4.png:images.ABI4.png:g
s:images/Motif.9.3.png:images.Motif.9.3.png:g
s:images/Motif.5.1.png:images.Motif.5.1.png:g
s:images/GimmeMotifs_1_genomic_matched_roc.png:images.GimmeMotifs_1_genomic_matched_roc.png:g
s:images/Motif.9.4.png:images.Motif.9.4.png:g
s:images/Average_28.png:images.Average_28.png:g
s:images/IRF2.png:images.IRF2.png:g
s:images/GimmeMotifs_4_genomic_matched_roc.png:images.GimmeMotifs_4_genomic_matched_roc.png:g
s:images/GimmeMotifs_7_genomic_matched_roc.png:images.GimmeMotifs_7_genomic_matched_roc.png:g
s:images/Motif.9.2.png:images.Motif.9.2.png:g
s:images/Motif.10.5.png:images.Motif.10.5.png:g
s:images/GimmeMotifs_2.png:images.GimmeMotifs_2.png:g
s:images/GimmeMotifs_3_histogram.svg:images.GimmeMotifs_3_histogram.svg:g
s:images/Meme_2_w9.png:images.Meme_2_w9.png:g
s:images/Motif.6.4.png:images.Motif.6.4.png:g
s:images/GimmeMotifs_3_genomic_matched_roc.png:images.GimmeMotifs_3_genomic_matched_roc.png:g
s:images/GimmeMotifs_4.png:images.GimmeMotifs_4.png:g
s:images/Meme_1_w10.png:images.Meme_1_w10.png:g
s:images/Meme_2_w8.png:images.Meme_2_w8.png:g
s:images/Motif.10.3.png:images.Motif.10.3.png:g
s:images/Meme_2_w10.png:images.Meme_2_w10.png:g
s:images/GABPA.png:images.GABPA.png:g
s:images/GimmeMotifs_5_random_roc.png:images.GimmeMotifs_5_random_roc.png:g
s:images/Motif.9.1.png:images.Motif.9.1.png:g
s:images/Meme_1_w9.png:images.Meme_1_w9.png:g
s:images/.png:images..png:g
s:images/Motif.7.4.png:images.Motif.7.4.png:g
s:images/Meme_2_w7.png:images.Meme_2_w7.png:g
s:images/box_1_3_nAGGAAGn.png:images.box_1_3_nAGGAAGn.png:g
s:images/GimmeMotifs_7_random_roc.png:images.GimmeMotifs_7_random_roc.png:g
s:images/GimmeMotifs_6_histogram.svg:images.GimmeMotifs_6_histogram.svg:g
s:images/Meme_4_w9.png:images.Meme_4_w9.png:g
s:images/GimmeMotifs_3_random_roc.png:images.GimmeMotifs_3_random_roc.png:g
s:images/Motif.9.6.png:images.Motif.9.6.png:g
s:images/GimmeMotifs_1.png:images.GimmeMotifs_1.png:g
s:images/GimmeMotifs_1_histogram.svg:images.GimmeMotifs_1_histogram.svg:g
s:images/box_1_7_rGGArGkGs.png:images.box_1_7_rGGArGkGs.png:g
s:images/Motif.10.2.png:images.Motif.10.2.png:g
s:images/GimmeMotifs_5.png:images.GimmeMotifs_5.png:g
s:images/SP1.png:images.SP1.png:g
s:images/Meme_9_w8.png:images.Meme_9_w8.png:g
s:images/Motif.10.1.png:images.Motif.10.1.png:g
s:images/GimmeMotifs_4_histogram.svg:images.GimmeMotifs_4_histogram.svg:g
s:images/GimmeMotifs_4_random_roc.png:images.GimmeMotifs_4_random_roc.png:g
s:images/box_1_9_AGGAAG.png:images.box_1_9_AGGAAG.png:g
s:images/GimmeMotifs_7.png:images.GimmeMotifs_7.png:g
s:images/GimmeMotifs_6_genomic_matched_roc.png:images.GimmeMotifs_6_genomic_matched_roc.png:g
s:images/GimmeMotifs_2_genomic_matched_roc.png:images.GimmeMotifs_2_genomic_matched_roc.png:g
s:images/Motif.8.1.png:images.Motif.8.1.png:g
s:images/Motif.8.4.png:images.Motif.8.4.png:g
s:images/GimmeMotifs_2_random_roc.png:images.GimmeMotifs_2_random_roc.png:g
s:images/Motif.7.5.png:images.Motif.7.5.png:g
s:images/GimmeMotifs_5_histogram.svg:images.GimmeMotifs_5_histogram.svg:g
s:images/GimmeMotifs_3.png:images.GimmeMotifs_3.png:g
s:images/GimmeMotifs_2_histogram.svg:images.GimmeMotifs_2_histogram.svg:g
s:images/box_1_7_CAGGAArnrn.png:images.box_1_7_CAGGAArnrn.png:g
s:images/box_1_2_CTTCC.png:images.box_1_2_CTTCC.png:g
s:images/Motif.10.4.png:images.Motif.10.4.png:g
s:images/GimmeMotifs_5_genomic_matched_roc.png:images.GimmeMotifs_5_genomic_matched_roc.png:g
s:images/Meme_7_w9.png:images.Meme_7_w9.png:g
s:images/GimmeMotifs_6.png:images.GimmeMotifs_6.png:g
s:images/Motif.7.1.png:images.Motif.7.1.png:g
s:intermediate_results/dataset_34056_files_bg_random.fa:intermediate_results.dataset_34056_files_bg_random.fa:g
s:intermediate_results/dataset_34056_files_bg_genomic_matched_enrichment_clustered.txt:intermediate_results.dataset_34056_files_bg_genomic_matched_enrichment_clustered.txt:g
s:intermediate_results/dataset_34056_files_significant_motifs.pfm:intermediate_results.dataset_34056_files_significant_motifs.pfm:g
s:intermediate_results/dataset_34056_files_bg_genomic_matched_enrichment.txt:intermediate_results.dataset_34056_files_bg_genomic_matched_enrichment.txt:g
s:intermediate_results/dataset_34056_files_validation_500.fa:intermediate_results.dataset_34056_files_validation_500.fa:g
s:intermediate_results/dataset_34056_files_bg_random_enrichment_clustered.txt:intermediate_results.dataset_34056_files_bg_random_enrichment_clustered.txt:g
s:intermediate_results/dataset_34056_files_bg_random_enrichment.txt:intermediate_results.dataset_34056_files_bg_random_enrichment.txt:g
s:intermediate_results/dataset_34056_files_clustered_motifs.pwm:intermediate_results.dataset_34056_files_clustered_motifs.pwm:g
s:intermediate_results/dataset_34056_files_prediction.bed:intermediate_results.dataset_34056_files_prediction.bed:g
s:intermediate_results/dataset_34056_files_bg_genomic_matched_significant_motifs_roc_metrics.txt:intermediate_results.dataset_34056_files_bg_genomic_matched_significant_motifs_roc_metrics.txt:g
s:intermediate_results/dataset_34056_files_bg_genomic_matched.gff:intermediate_results.dataset_34056_files_bg_genomic_matched.gff:g
s:intermediate_results/dataset_34056_files_validation.bed:intermediate_results.dataset_34056_files_validation.bed:g
s:intermediate_results/dataset_34056_files_prediction.fa:intermediate_results.dataset_34056_files_prediction.fa:g
s:intermediate_results/dataset_34056_files_validation_clustered.gff:intermediate_results.dataset_34056_files_validation_clustered.gff:g
s:intermediate_results/dataset_34056_files_significant_motifs.pwm:intermediate_results.dataset_34056_files_significant_motifs.pwm:g
s:intermediate_results/dataset_34056_files_bg_random_significant_motifs_roc_metrics.txt:intermediate_results.dataset_34056_files_bg_random_significant_motifs_roc_metrics.txt:g
s:intermediate_results/dataset_34056_files_all_motifs.pwm:intermediate_results.dataset_34056_files_all_motifs.pwm:g
s:intermediate_results/dataset_34056_files_validation.fa:intermediate_results.dataset_34056_files_validation.fa:g
s:intermediate_results/dataset_34056_files_peakinputfile.bed:intermediate_results.dataset_34056_files_peakinputfile.bed:g
s:intermediate_results/dataset_34056_files_bg_random.gff:intermediate_results.dataset_34056_files_bg_random.gff:g
s:intermediate_results/dataset_34056_files_bg_genomic_matched.fa:intermediate_results.dataset_34056_files_bg_genomic_matched.fa:g
s:intermediate_results/dataset_34056_files_validation.gff:intermediate_results.dataset_34056_files_validation.gff:g
s:intermediate_results/dataset_34056_files_prediction_background.fa:intermediate_results.dataset_34056_files_prediction_background.fa:g
s:intermediate_results/dataset_34056_files_all_motifs.pfm:intermediate_results.dataset_34056_files_all_motifs.pfm:g
